
```{r}
library(GeneSPLS)
library(spls)
library(microbenchmark)
library(bench)

knitr::opts_chunk$set(
  cache = TRUE,
  warning = FALSE,
  message = FALSE,
  cache.lazy = FALSE)

data("UniReal") # load data
source(here::here("dev", "coef_valid.R"))
```


### CROSS-VALIDATION

```{r CV, warning = FALSE}
set.seed(226)


# Define candidate parameters
eta_candidates <- seq(0.95, 0.99, by = 0.01)
K_candidates <- 1:10

# spls

cv_uni_real_R <- cv.spls(
  X_uni_real,
  Y_uni_real,
  fold = 5,
  eta = eta_candidates,
  K = K_candidates,
  kappa = 0.5,
  select = "pls2",
  fit = "widekernelpls",
  scale.x = TRUE,
  scale.y = FALSE,
  plot.it = FALSE)


# GeneSPLS

cv_uni_real_Cpp <- cv_spls_cpp(
  X_uni_real,
  Y_uni_real,
  fold = 5,
  eta = eta_candidates,
  K = K_candidates,
  kappa = 0.5,
  select = "pls2",
  scale_x = TRUE,
  scale_y = FALSE,
  eps = 1e-4,
  maxstep = 100,
  trace = FALSE)

eta_uni_real_R <- cv_uni_real_R$eta.opt
K_uni_real_R <- cv_uni_real_R$K.opt
eta_uni_real_Cpp <- cv_uni_real_Cpp$eta.opt
K_uni_real_Cpp <- cv_uni_real_Cpp$K.opt
rm(cv_uni_real_R, cv_uni_real_Cpp)
```


### SPLS MODEL FITTING

```{r SPLS, warning = FALSE}
set.seed(815)


# spls

spls_uni_real_R <- spls(
  X_uni_real,
  Y_uni_real,
  K = K_uni_real_Cpp,
  eta = eta_uni_real_Cpp,
  fit = "widekernelpls")


# GeneSPLS

spls_uni_real_Cpp <- spls_cpp(
  X,
  AKT3_Expression,
  K = K_uni_real_Cpp,
  eta = eta_uni_real_Cpp,
  kappa = 0.5,
  select = "pls2",
  fit = "widekernelpls",
  scale_x = TRUE,
  scale_y = FALSE,
  eps = 1e-4,
  maxstep = 100,
  trace = FALSE)

# Valid coefficients match
coef_valid(
  coef(spls_uni_real_R),
  spls_uni_real_Cpp$betahat,
  tolerance = 1e-6
)
```


### BENCHMARKING

```{r benchmarking, warning = FALSE}
set.seed(815)


### CV BENCHMARK ###

bench_cv_uni_real <- microbenchmark(
  
  cv_uni_real_R = cv.spls(
    X_uni_real,
    Y_uni_real,
    fold = 5,
    eta = eta_candidates,
    K = K_candidates,
    kappa = 0.5,
    select = "pls2",
    fit = "widekernelpls",
    scale.x = TRUE,
    scale.y = FALSE,
    plot.it = FALSE),
  
  cv_uni_real_Cpp <- cv_spls_cpp(
    X_uni_real,
    Y_uni_real,
    fold = 5,
    eta = eta_candidates,
    K = K_candidates,
    kappa = 0.5,
    select = "pls2",
    scale_x = TRUE,
    scale_y = FALSE,
    eps = 2e-3,
    maxstep = 10000,
    trace = FALSE),
  
  times = 3
)


### MODEL BENCHMARK ###

bench_spls_uni_real <- microbenchmark(
  
  spls_uni_real_R = spls(
    X_uni_real,
    Y_uni_real,
    K = K_uni_real_Cpp,
    eta = eta_uni_real_Cpp,
    fit = "widekernelpls"),
  
  spls_uni_real_Cpp = spls_cpp(
    X_uni_real,
    Y_uni_real,
    K = K_uni_real_Cpp,
    eta = eta_uni_real_Cpp,
    kappa = 0.5,
    select = "pls2",
    fit = "widekernelpls",
    scale_x = TRUE,
    scale_y = FALSE,
    eps = 1e-4,
    maxstep = 100,
    trace = FALSE),
  
  times = 50
)
```

```{r benchmark results}
print(bench_cv_uni_real) # CV benchmark results
print(bench_spls_uni_real) # SPLS benchmark results
```

```{r benchmark2}
result = bench::mark(
  
  spls_uni_real_R = spls(
    X_uni_real,
    Y_uni_real,
    K = K_uni_real_Cpp,
    eta = eta_uni_real_Cpp,
    fit = "widekernelpls"),
  
  spls_uni_real_Cpp = spls_cpp(
    X_uni_real,
    Y_uni_real,
    K = K_uni_real_Cpp,
    eta = eta_uni_real_Cpp,
    kappa = 0.5,
    select = "pls2",
    fit = "widekernelpls",
    scale_x = TRUE,
    scale_y = FALSE,
    eps = 1e-4,
    maxstep = 100,
    trace = FALSE),
  
  check = F,
  
  iterations = 20
)

print(result)
```

