# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name correctp
#' @title Parameter validation for SPLS
#' 
#' @description Validates and corrects parameters for the SPLS algorithm
#' 
#' @param X Predictor matrix
#' @param Y Response matrix
#' @param eta Sparsity parameter between 0 and 1
#' @param K Number of components
#' @param kappa Parameter between 0 and 0.5
#' @param select Selection method ("pls2" or "simpls")
#' @param fit Fitting method
#' @return List with validated parameters
#' 
#' @export
correctp <- function(X, Y, eta, K, kappa, select, fit) {
    .Call(`_GeneSPLS_correctp`, X, Y, eta, K, kappa, select, fit)
}

#' @name widekernelpls_fit
#' @title Wide Kernel PLS Algorithm Implementation
#'
#' @description This function implements the wide kernel PLS algorithm as described by
#' Rannar et al. (1994). It's optimized for datasets with more variables than observations.
#'
#' @param X Predictor matrix (n x p), p is the number of predictors
#' @param Y Response matrix (n x m), m is the number of responses
#' @param ncomp Number of components to extract
#' @param center Logical, whether to center X and Y (default: true)
#' @param tol Numeric, tolerance used for determining convergence (default: 1.5e-8)
#' @param maxit Integer, maximum number of iterations (default: 100)
#'
#' @return A list containing:
#' \item{coefficients}{The regression coefficients matrix}
#' \item{projection}{The projection matrix}
#' \item{Xmeans}{The column means of X (if centered)}
#' \item{Ymeans}{The column means of Y (if centered)}
#' 
#' @useDynLib GeneSPLS, .registration = TRUE
#' @import Rcpp
#' 
#' @examples
#' 
#' set.seed(815)
#' 
#' # Simulating high-dimensional predictor matrix (p >> n)
#' n <- 10   # Number of observations
#' p <- 20  # Number of predictors
#' 
#' X <- matrix(rnorm(n * p), nrow = n, ncol = p)  # Random normal predictors
#' 
#' # True coefficients: Only first 5 predictors contribute to Y
#' beta <- c(rnorm(5, sd = 2), rep(0, p - 5))
#' 
#' # Generating response variable Y with N(0,1) noise
#' Y <- X %*% beta + rnorm(n)
#' 
#' 
#' pls_cpp = GeneSPLS::widekernelpls_fit(X, Y, 5, center = FALSE)
#' pls_cpp$projection
#' pls_cpp$coefficients
#'
#' @export
widekernelpls_fit <- function(X, Y, ncomp, center = TRUE, tol = 1.5e-8, maxit = 100L) {
    .Call(`_GeneSPLS_widekernelpls_fit`, X, Y, ncomp, center, tol, maxit)
}

#' @name spls_cpp
#' @title Sparse Partial Least Squares Regression
#'
#' @description C++ implementation of the Sparse Partial Least Squares algorithm
#' 
#' @param x Predictor matrix (n x p)
#' @param y Response matrix (n x q)
#' @param K Number of latent components
#' @param eta Sparsity parameter, 0 < eta < 1
#' @param kappa If y is multivariate, 0 < kappa <= 0.5
#' @param select Method for variable selection: "pls2" (update Y) or "simpls" (update X)
#' @param fit Always "widekernelpls" in this implementation
#' @param scale_x Whether to scale the predictor matrix
#' @param scale_y Whether to scale the response matrix
#' @param eps Convergence criterion for direction vector calculation
#' @param maxstep Maximum number of iterations for direction vector calculation
#' @param trace Whether to print progress information
#' 
#' @return A list containing model information including:
#' \item{betahat}{Regression coefficients}
#' \item{A}{Active set of predictors}
#' \item{projection}{Projection matrix}
#' 
#' @useDynLib GeneSPLS, .registration = TRUE
#' @import Rcpp
#' 
#' @export
spls_cpp <- function(x, y, K, eta, kappa = 0.5, select = "pls2", fit = "widekernelpls", scale_x = TRUE, scale_y = FALSE, eps = 1e-4, maxstep = 100L, trace = FALSE) {
    .Call(`_GeneSPLS_spls_cpp`, x, y, K, eta, kappa, select, fit, scale_x, scale_y, eps, maxstep, trace)
}

#' @name ust
#' @title Univariate Soft Thresholding (UST) Function
#' 
#' @description Performs soft thresholding on a vector
#' 
#' @param b Vector to be thresholded
#' @param eta Threshold parameter between 0 and 1
#' @return Soft thresholded vector
NULL

#' @name spls_dv
#' @title Sparse PLS Direction Vector Estimation
#' 
#' @description Calculates the direction vector for Sparse PLS
#' 
#' @param Z Cross-product matrix (p x q)
#' @param eta Sparsity parameter between 0 and 1
#' @param kappa Parameter between 0 and 0.5
#' @param eps Convergence criterion
#' @param maxstep Maximum number of iterations
#' @return Direction vector
#' 
#' @export
spls_dv <- function(Z, eta, kappa, eps, maxstep) {
    .Call(`_GeneSPLS_spls_dv`, Z, eta, kappa, eps, maxstep)
}

